spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_v2
    username: postgres
    password: mine8465
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /data-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework.jdbc: trace



