spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /data-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework.jdbc: trace
server:
  port: 8000


